import defaultTheme from 'tailwindcss/defaultTheme';
import colors from 'tailwindcss/colors';
import forms from '@tailwindcss/forms';
import aspectRatio from '@tailwindcss/aspect-ratio';

const htr = (h) => {
    let r = 0, g = 0, b = 0;
    if (h.length === 4) {
        r = '0x' + h[1] + h[1];
        g = '0x' + h[2] + h[2];
        b = '0x' + h[3] + h[3];
    } else if (h.length === 7) {
        r = '0x' + h[1] + h[2];
        g = '0x' + h[3] + h[4];
        b = '0x' + h[5] + h[6];
    }
    return +r + ' ' + +g + ' ' + +b;
};

const wov = (v) => {
    return ({ ov }) => {
        if (ov === undefined) {
            return `rgb(var(${v}))`;
        }
        return `rgb(var(${v}) / ${ov})`;
    };
};

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        skin: {
            white: htr(colors.white),
            sky: {
                DEFAULT: htr(colors.sky[600]),
                50: htr(colors.sky[50]),
                100: htr(colors.sky[100]),
                200: htr(colors.sky[200]),
                300: htr(colors.sky[300]),
                400: htr(colors.sky[400]),
                500: htr(colors.sky[500]),
                600: htr(colors.sky[600]),
                700: htr(colors.sky[700]),
                800: htr(colors.sky[800]),
                900: htr(colors.sky[900]),
                950: htr(colors.sky[950]),
            },
            red: {
                DEFAULT: htr(colors.red[600]),
                50: htr(colors.red[50]),
                100: htr(colors.red[100]),
                200: htr(colors.red[200]),
                300: htr(colors.red[300]),
                400: htr(colors.red[400]),
                500: htr(colors.red[500]),
                600: htr(colors.red[600]),
                700: htr(colors.red[700]),
                800: htr(colors.red[800]),
                900: htr(colors.red[900]),
                950: htr(colors.red[950]),
            },
            orange: {
                DEFAULT: htr(colors.orange[600]),
                50: htr(colors.orange[50]),
                100: htr(colors.orange[100]),
                200: htr(colors.orange[200]),
                300: htr(colors.orange[300]),
                400: htr(colors.orange[400]),
                500: htr(colors.orange[500]),
                600: htr(colors.orange[600]),
                700: htr(colors.orange[700]),
                800: htr(colors.orange[800]),
                900: htr(colors.orange[900]),
                950: htr(colors.orange[950]),
            },
            amber: {
                DEFAULT: htr(colors.amber[600]),
                50: htr(colors.amber[50]),
                100: htr(colors.amber[100]),
                200: htr(colors.amber[200]),
                300: htr(colors.amber[300]),
                400: htr(colors.amber[400]),
                500: htr(colors.amber[500]),
                600: htr(colors.amber[600]),
                700: htr(colors.amber[700]),
                800: htr(colors.amber[800]),
                900: htr(colors.amber[900]),
                950: htr(colors.amber[950]),
            },
            yellow: {
                DEFAULT: htr(colors.yellow[600]),
                50: htr(colors.yellow[50]),
                100: htr(colors.yellow[100]),
                200: htr(colors.yellow[200]),
                300: htr(colors.yellow[300]),
                400: htr(colors.yellow[400]),
                500: htr(colors.yellow[500]),
                600: htr(colors.yellow[600]),
                700: htr(colors.yellow[700]),
                800: htr(colors.yellow[800]),
                900: htr(colors.yellow[900]),
                950: htr(colors.yellow[950]),
            },
            lime: {
                DEFAULT: htr(colors.lime[600]),
                50: htr(colors.lime[50]),
                100: htr(colors.lime[100]),
                200: htr(colors.lime[200]),
                300: htr(colors.lime[300]),
                400: htr(colors.lime[400]),
                500: htr(colors.lime[500]),
                600: htr(colors.lime[600]),
                700: htr(colors.lime[700]),
                800: htr(colors.lime[800]),
                900: htr(colors.lime[900]),
                950: htr(colors.lime[950]),
            },
            green: {
                DEFAULT: htr(colors.green[600]),
                50: htr(colors.green[50]),
                100: htr(colors.green[100]),
                200: htr(colors.green[200]),
                300: htr(colors.green[300]),
                400: htr(colors.green[400]),
                500: htr(colors.green[500]),
                600: htr(colors.green[600]),
                700: htr(colors.green[700]),
                800: htr(colors.green[800]),
                900: htr(colors.green[900]),
                950: htr(colors.green[950]),
            },
            emerald: {
                DEFAULT: htr(colors.emerald[600]),
                50: htr(colors.emerald[50]),
                100: htr(colors.emerald[100]),
                200: htr(colors.emerald[200]),
                300: htr(colors.emerald[300]),
                400: htr(colors.emerald[400]),
                500: htr(colors.emerald[500]),
                600: htr(colors.emerald[600]),
                700: htr(colors.emerald[700]),
                800: htr(colors.emerald[800]),
                900: htr(colors.emerald[900]),
                950: htr(colors.emerald[950]),
            },
            teal: {
                DEFAULT: htr(colors.teal[600]),
                50: htr(colors.teal[50]),
                100: htr(colors.teal[100]),
                200: htr(colors.teal[200]),
                300: htr(colors.teal[300]),
                400: htr(colors.teal[400]),
                500: htr(colors.teal[500]),
                600: htr(colors.teal[600]),
                700: htr(colors.teal[700]),
                800: htr(colors.teal[800]),
                900: htr(colors.teal[900]),
                950: htr(colors.teal[950]),
            },
            cyan: {
                DEFAULT: htr(colors.cyan[600]),
                50: htr(colors.cyan[50]),
                100: htr(colors.cyan[100]),
                200: htr(colors.cyan[200]),
                300: htr(colors.cyan[300]),
                400: htr(colors.cyan[400]),
                500: htr(colors.cyan[500]),
                600: htr(colors.cyan[600]),
                700: htr(colors.cyan[700]),
                800: htr(colors.cyan[800]),
                900: htr(colors.cyan[900]),
                950: htr(colors.cyan[950]),
            },
            blue: {
                DEFAULT: htr(colors.blue[600]),
                50: htr(colors.blue[50]),
                100: htr(colors.blue[100]),
                200: htr(colors.blue[200]),
                300: htr(colors.blue[300]),
                400: htr(colors.blue[400]),
                500: htr(colors.blue[500]),
                600: htr(colors.blue[600]),
                700: htr(colors.blue[700]),
                800: htr(colors.blue[800]),
                900: htr(colors.blue[900]),
                950: htr(colors.blue[950]),
            },
            indigo: {
                DEFAULT: htr(colors.indigo[600]),
                50: htr(colors.indigo[50]),
                100: htr(colors.indigo[100]),
                200: htr(colors.indigo[200]),
                300: htr(colors.indigo[300]),
                400: htr(colors.indigo[400]),
                500: htr(colors.indigo[500]),
                600: htr(colors.indigo[600]),
                700: htr(colors.indigo[700]),
                800: htr(colors.indigo[800]),
                900: htr(colors.indigo[900]),
                950: htr(colors.indigo[950]),
            },
            violet: {
                DEFAULT: htr(colors.violet[600]),
                50: htr(colors.violet[50]),
                100: htr(colors.violet[100]),
                200: htr(colors.violet[200]),
                300: htr(colors.violet[300]),
                400: htr(colors.violet[400]),
                500: htr(colors.violet[500]),
                600: htr(colors.violet[600]),
                700: htr(colors.violet[700]),
                800: htr(colors.violet[800]),
                900: htr(colors.violet[900]),
                950: htr(colors.violet[950]),
            },
            purple: {
                DEFAULT: htr(colors.purple[600]),
                50: htr(colors.purple[50]),
                100: htr(colors.purple[100]),
                200: htr(colors.purple[200]),
                300: htr(colors.purple[300]),
                400: htr(colors.purple[400]),
                500: htr(colors.purple[500]),
                600: htr(colors.purple[600]),
                700: htr(colors.purple[700]),
                800: htr(colors.purple[800]),
                900: htr(colors.purple[900]),
                950: htr(colors.purple[950]),
            },
            fuchsia: {
                DEFAULT: htr(colors.fuchsia[600]),
                50: htr(colors.fuchsia[50]),
                100: htr(colors.fuchsia[100]),
                200: htr(colors.fuchsia[200]),
                300: htr(colors.fuchsia[300]),
                400: htr(colors.fuchsia[400]),
                500: htr(colors.fuchsia[500]),
                600: htr(colors.fuchsia[600]),
                700: htr(colors.fuchsia[700]),
                800: htr(colors.fuchsia[800]),
                900: htr(colors.fuchsia[900]),
                950: htr(colors.fuchsia[950]),
            },
            pink: {
                DEFAULT: htr(colors.pink[600]),
                50: htr(colors.pink[50]),
                100: htr(colors.pink[100]),
                200: htr(colors.pink[200]),
                300: htr(colors.pink[300]),
                400: htr(colors.pink[400]),
                500: htr(colors.pink[500]),
                600: htr(colors.pink[600]),
                700: htr(colors.pink[700]),
                800: htr(colors.pink[800]),
                900: htr(colors.pink[900]),
                950: htr(colors.pink[950]),
            },
            rose: {
                DEFAULT: htr(colors.rose[600]),
                50: htr(colors.rose[50]),
                100: htr(colors.rose[100]),
                200: htr(colors.rose[200]),
                300: htr(colors.rose[300]),
                400: htr(colors.rose[400]),
                500: htr(colors.rose[500]),
                600: htr(colors.rose[600]),
                700: htr(colors.rose[700]),
                800: htr(colors.rose[800]),
                900: htr(colors.rose[900]),
                950: htr(colors.rose[950]),
            },
            gray: {
                50: htr(colors.gray[50]),
                100: htr(colors.gray[100]),
                200: htr(colors.gray[200]),
                300: htr(colors.gray[300]),
                400: htr(colors.gray[400]),
                500: htr(colors.gray[500]),
                600: htr(colors.gray[600]),
                700: htr(colors.gray[700]),
                800: htr(colors.gray[800]),
                900: htr(colors.gray[900]),
                950: htr(colors.gray[950]),
            },
            slate: {
                50: htr(colors.slate[50]),
                100: htr(colors.slate[100]),
                200: htr(colors.slate[200]),
                300: htr(colors.slate[300]),
                400: htr(colors.slate[400]),
                500: htr(colors.slate[500]),
                600: htr(colors.slate[600]),
                700: htr(colors.slate[700]),
                800: htr(colors.slate[800]),
                900: htr(colors.slate[900]),
                950: htr(colors.slate[950]),
            },
            zinc: {
                50: htr(colors.zinc[50]),
                100: htr(colors.zinc[100]),
                200: htr(colors.zinc[200]),
                300: htr(colors.zinc[300]),
                400: htr(colors.zinc[400]),
                500: htr(colors.zinc[500]),
                600: htr(colors.zinc[600]),
                700: htr(colors.zinc[700]),
                800: htr(colors.zinc[800]),
                900: htr(colors.zinc[900]),
                950: htr(colors.zinc[950]),
            },
            neutral: {
                50: htr(colors.neutral[50]),
                100: htr(colors.neutral[100]),
                200: htr(colors.neutral[200]),
                300: htr(colors.neutral[300]),
                400: htr(colors.neutral[400]),
                500: htr(colors.neutral[500]),
                600: htr(colors.neutral[600]),
                700: htr(colors.neutral[700]),
                800: htr(colors.neutral[800]),
                900: htr(colors.neutral[900]),
                950: htr(colors.neutral[950]),
            },
            stone: {
                50: htr(colors.stone[50]),
                100: htr(colors.stone[100]),
                200: htr(colors.stone[200]),
                300: htr(colors.stone[300]),
                400: htr(colors.stone[400]),
                500: htr(colors.stone[500]),
                600: htr(colors.stone[600]),
                700: htr(colors.stone[700]),
                800: htr(colors.stone[800]),
                900: htr(colors.stone[900]),
                950: htr(colors.stone[950]),
            },
            secondary: {
                DEFAULT: htr(colors.gray[400]),
            },
        },
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: colors.black,
            white: colors.white,
            sky: colors.sky,
            red: colors.red,
            orange: colors.orange,
            amber: colors.amber,
            yellow: colors.yellow,
            lime: colors.lime,
            green: colors.green,
            emerald: colors.emerald,
            teal: colors.teal,
            cyan: colors.cyan,
            blue: colors.blue,
            indigo: colors.indigo,
            violet: colors.violet,
            purple: colors.purple,
            fuchsia: colors.fuchsia,
            pink: colors.pink,
            rose: colors.rose,
            slate: colors.slate,
            zinc: colors.zinc,
            neutral: colors.neutral,
            stone: colors.stone,
            gray: {
                50: wov('--color-gray-50'),
                100: wov('--color-gray-100'),
                200: wov('--color-gray-200'),
                300: wov('--color-gray-300'),
                400: wov('--color-gray-400'),
                500: wov('--color-gray-500'),
                600: wov('--color-gray-600'),
                700: wov('--color-gray-700'),
                800: wov('--color-gray-800'),
                900: wov('--color-gray-900'),
                950: wov('--color-gray-950'),
            },
            primary: {
                DEFAULT: wov('--color-primary'),
                50: wov('--color-primary-50'),
                100: wov('--color-primary-100'),
                200: wov('--color-primary-200'),
                300: wov('--color-primary-300'),
                400: wov('--color-primary-400'),
                500: wov('--color-primary-500'),
                600: wov('--color-primary-600'),
                700: wov('--color-primary-700'),
                800: wov('--color-primary-800'),
                900: wov('--color-primary-900'),
                950: wov('--color-primary-950'),
            },
            secondary: wov('--color-secondary'),
        },
        extend: {
            rotate: {
                '225': '225deg',
            },
            animation: {
                fadeInTop: 'fadeInTop 0.5s ease-out forwards',
            },
            keyframes: {
                fadeInTop: {
                    '0%': {
                        filter: 'blur(4px)',
                        transform: 'translateY(-0.25rem)',
                    },
                    '100%': {
                        filter: '',
                        transform: 'translateY(0rem)',
                    },
                },
            },
            fontFamily: {
                sans: ['var(--font-body), Sarabun', ...defaultTheme.fontFamily.sans],
                body: ['var(--font-body), Sarabun', ...defaultTheme.fontFamily.sans],
                head: ['var(--font-head), Sarabun', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                success: '#28a745',
                danger: '#dc3545',
                warning: '#ffc107',
                info: '#17a2b8',
                social: {
                    facebook: '#3b5998',
                    x: '#1da1f2',
                    pinterest: '#bd081c',
                    whatsapp: '#25d366',
                },
            },
            backgroundColor: {
                background: wov('--color-background'),
                component: wov('--color-component'),
                input: wov('--color-input'),
            },
            borderColor: {
                divider: wov('--color-divider'),
                border: wov('--color-border'),
            },
            textColor: {
                normal: wov('--color-text-normal'),
                muted: wov('--color-text-muted'),
            },
        },
    },

    plugins: [forms, aspectRatio],
};
